import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

import { ReduxProvider } from "@/shared/lib/redux-provider";
import WaitlistPage from "./waitlist/page";
import { Toaster } from "react-hot-toast";
import { AppLayout } from "./AppLayout";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// const inter = Inter({
//   subsets: ["latin"],
//   variable: "--font-inter",
// });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const showWaitlist = process.env.SHOW_WAITLIST === "true";
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {showWaitlist ? (
          <WaitlistPage />
        ) : (
          <>
            <ReduxProvider>
              <AppLayout>{children}</AppLayout>
            </ReduxProvider>
          </>
        )}
        <Toaster position="top-right" />
      </body>
    </html>
  );
}
