import { Vehicle } from "@/entities/vehicle/model/types";
import card1 from "../../../../public/assets/images/car1.png";

// Mock или real fetch
export async function getFeaturedVehicles(): Promise<Vehicle[]> {
  return [
    {
      id: "1",
      title: "Mercedes-Benz S-Class",
      year: 2007,
      mileage: 18200,
      transmission: "Manual",
      fuel: "Diesel",
      engine: "3 L",
      location: "Miami, FL",
      price: 10900,
      image: "../../../../public/assets/images/car1.png",
      isFavorite: false,
      date: "Today",
    },
    {
      id: "1",
      title: "Mercedes-Benz S-Class",
      year: 2007,
      mileage: 18200,
      transmission: "Manual",
      fuel: "Diesel",
      engine: "3 L",
      location: "Miami, FL",
      price: 10900,
      image: "../../../../public/assets/images/car1.png",
      isFavorite: false,
      date: "Today",
    },
    {
      id: "1",
      title: "Mercedes-Benz S-Class",
      year: 2007,
      mileage: 18200,
      transmission: "Manual",
      fuel: "Diesel",
      engine: "3 L",
      location: "Miami, FL",
      price: 10900,
      image: "../../../../public/assets/images/car1.png",
      isFavorite: false,
      date: "Today",
    },
    {
      id: "1",
      title: "Mercedes-Benz S-Class",
      year: 2007,
      mileage: 18200,
      transmission: "Manual",
      fuel: "Diesel",
      engine: "3 L",
      location: "Miami, FL",
      price: 10900,
      image: "../../../../public/assets/images/car1.png",
      isFavorite: false,
      date: "Today",
    },
    {
      id: "1",
      title: "Mercedes-Benz S-Class",
      year: 2007,
      mileage: 18200,
      transmission: "Manual",
      fuel: "Diesel",
      engine: "3 L",
      location: "Miami, FL",
      price: 10900,
      image: "../../../../public/assets/images/car1.png",
      isFavorite: false,
      date: "Today",
    },
    {
      id: "1",
      title: "Mercedes-Benz S-Class",
      year: 2007,
      mileage: 18200,
      transmission: "Manual",
      fuel: "Diesel",
      engine: "3 L",
      location: "Miami, FL",
      price: 10900,
      image: "../../../../public/assets/images/car1.png",
      isFavorite: false,
      date: "Today",
    },
    {
      id: "1",
      title: "Mercedes-Benz S-Class",
      year: 2007,
      mileage: 18200,
      transmission: "Manual",
      fuel: "Diesel",
      engine: "3 L",
      location: "Miami, FL",
      price: 10900,
      image: "../../../../public/assets/images/car1.png",
      isFavorite: false,
      date: "Today",
    },
    {
      id: "1",
      title: "Mercedes-Benz S-Class",
      year: 2007,
      mileage: 18200,
      transmission: "Manual",
      fuel: "Diesel",
      engine: "3 L",
      location: "Miami, FL",
      price: 10900,
      image: "../../../../public/assets/images/car1.png",
      isFavorite: false,
      date: "Today",
    },
    {
      id: "1",
      title: "Mercedes-Benz S-Class",
      year: 2007,
      mileage: 18200,
      transmission: "Manual",
      fuel: "Diesel",
      engine: "3 L",
      location: "Miami, FL",
      price: 10900,
      image: "../../../../public/assets/images/car1.png",
      isFavorite: false,
      date: "Today",
    },
    {
      id: "1",
      title: "Mercedes-Benz S-Class",
      year: 2007,
      mileage: 18200,
      transmission: "Manual",
      fuel: "Diesel",
      engine: "3 L",
      location: "Miami, FL",
      price: 10900,
      image: "../../../../public/assets/images/car1.png",
      isFavorite: false,
      date: "Today",
    },
    {
      id: "1",
      title: "Mercedes-Benz S-Class",
      year: 2007,
      mileage: 18200,
      transmission: "Manual",
      fuel: "Diesel",
      engine: "3 L",
      location: "Miami, FL",
      price: 10900,
      image: "../../../../public/assets/images/car1.png",
      isFavorite: false,
      date: "Today",
    },
    {
      id: "1",
      title: "Mercedes-Benz S-Class",
      year: 2007,
      mileage: 18200,
      transmission: "Manual",
      fuel: "Diesel",
      engine: "3 L",
      location: "Miami, FL",
      price: 10900,
      image: "../../../../public/assets/images/car1.png",
      isFavorite: false,
      date: "Today",
    },
    {
      id: "1",
      title: "Mercedes-Benz S-Class",
      year: 2007,
      mileage: 18200,
      transmission: "Manual",
      fuel: "Diesel",
      engine: "3 L",
      location: "Miami, FL",
      price: 10900,
      image: "../../../../public/assets/images/car1.png",
      isFavorite: false,
      date: "Today",
    },
    {
      id: "1",
      title: "Mercedes-Benz S-Class",
      year: 2007,
      mileage: 18200,
      transmission: "Manual",
      fuel: "Diesel",
      engine: "3 L",
      location: "Miami, FL",
      price: 10900,
      image: "../../../../public/assets/images/car1.png",
      isFavorite: false,
      date: "Today",
    },
    {
      id: "2",
      title: "Mercedes-Benz S-Class",
      year: 2007,
      mileage: 18200,
      transmission: "Manual",
      fuel: "Diesel",
      engine: "3 L",
      location: "Miami, FL",
      price: 10900,
      image: "../../../../public/assets/images/car1.png",
      isFavorite: false,
      date: "Today",
    },
    {
      id: "3",
      title: "Mercedes-Benz S-Class",
      year: 2007,
      mileage: 18200,
      transmission: "Manual",
      fuel: "Diesel",
      engine: "3 L",
      location: "Miami, FL",
      price: 10900,
      image: "../../../../public/assets/images/car1.png",
      isFavorite: false,
      date: "Today",
    },
    {
      id: "4",
      title: "Mercedes-Benz S-Class",
      year: 2007,
      mileage: 18200,
      transmission: "Manual",
      fuel: "Diesel",
      engine: "3 L",
      location: "Miami, FL",
      price: 10900,
      image: "../../../../public/assets/images/car1.png",
      isFavorite: false,
      date: "Today",
    },

    // другие авто
  ];
}
